"""Post-process the models generated by @hey-api/openapi-python.

The patches below work around places where the generated code disagrees with
either the API or the rest of this package:

* generated enum classes are unusable here - the sandbox ``resources`` values
  ("1x2", "2x4", ...) become identifiers starting with a digit, so the module
  does not even compile,
* environment IDs are hashid strings typed as int32,
* ``POST /sandboxes`` accepts ``scope``/``environment`` in the body while
  documenting three records declaring neither,
* the create-sandbox body union must be matched in declaration order, or
  pydantic's smart union silently drops ``snapshot_id``,
* models reference type aliases declared further down the file, which only
  resolves on Python 3.14+ unless annotations are deferred,
* the module declares no ``__all__``, so the package cannot re-export it.

Each patch raises once it stops applying, so the next regeneration fails loudly
rather than keeping a stale workaround.
"""

from __future__ import annotations

import re
import sys
from collections.abc import Callable
from pathlib import Path

DEFAULT_TARGET = Path("src/buddy_sandbox/api/openapi/pydantic_gen.py")

REPORT = "check whether the generated code still needs this workaround"

ENVIRONMENT_REF = '''class SandboxEnvironmentRef(BaseModel):
    """The environment a sandbox belongs to."""

    id: Optional[str] = Field(default=None, description="The ID of the environment")
    identifier: Optional[str] = Field(default=None, description="The human-readable identifier of the environment")
    name: Optional[str] = Field(default=None, description="The name of the environment")


'''

ENVIRONMENT_FIELDS = """    scope: Optional[Literal["PROJECT", "ENVIRONMENT", "WORKSPACE"]] = Field(default=None, description="The scope of the sandbox: PROJECT, ENVIRONMENT, or WORKSPACE")
    environment: Optional[SandboxEnvironmentRef] = Field(default=None, description="The environment the sandbox belongs to (required when scope is `ENVIRONMENT`)")
"""

CREATE_BODY_MODELS = (
    "CloneSandboxRequest",
    "CreateFromSnapshotRequestWritable",
    "CreateNewSandboxRequestWritable",
)

HASHID_MODELS = ("ShortEnvironmentView", "ShortEnvironmentViewWritable")

BLOCK_SEPARATOR = "\n\n\n"

ENUM_CLASS = re.compile(
    r"^class (\w+)\((?:str, )?Enum\):\n"
    r'(?:    """[^\n]*"""\n)?'
    r"\n"
    r"((?:    \w+ = [^\n]*\n)+)",
    re.MULTILINE,
)

ENUM_MEMBER = re.compile(r"^    \w+ = (.+)$", re.MULTILINE)


def class_block(name: str) -> re.Pattern[str]:
    """Match a generated class from its ``class`` line up to the blank gap."""
    return re.compile(
        rf"^class {name}\(.*?(?={re.escape(BLOCK_SEPARATOR)})", re.DOTALL | re.MULTILINE
    )


def patch_block(
    content: str,
    pattern: re.Pattern[str],
    transform: Callable[[str], str],
    what: str,
) -> str:
    """Replace a generated block, insisting that the patch still has an effect."""
    match = pattern.search(content)

    if match is None:
        raise SystemExit(
            f"Patch target no longer exists: {what}. The generated shape changed - "
            f"re-check whether the workaround is still needed ({REPORT})."
        )

    block = match.group(0)
    patched = transform(block)

    if patched == block:
        raise SystemExit(
            f"Patch is now a no-op: {what}. This most likely means the generated code "
            f"already does the right thing - delete the workaround ({REPORT})."
        )

    return content[: match.start()] + patched + content[match.end() :]


def append_fields(block: str, fields: str) -> str:
    """Append fields to a generated model, after its last declared one."""
    return f"{block.rstrip()}\n{fields.rstrip()}"


def drop_blocks(content: str, pattern: re.Pattern[str]) -> str:
    """Drop every top-level block whose first line matches."""
    blocks = content.split(BLOCK_SEPARATOR)
    return BLOCK_SEPARATOR.join(block for block in blocks if not pattern.match(block))


def defer_annotations(content: str) -> str:
    """Add ``from __future__ import annotations`` to the generated module.

    Models reference type aliases (``TargetView``, ...) that the generator emits
    *below* their first use. Python 3.14 defers annotation evaluation and does
    not care, but every earlier version raises ``NameError`` at import. Deferring
    them explicitly keeps the module importable on the whole supported range.
    """
    marker = "from __future__ import annotations\n"

    if marker in content:
        raise SystemExit(
            f"Patch is now a no-op: the generator already defers annotations - "
            f"delete the workaround ({REPORT})."
        )

    header, _, rest = content.partition("\n")

    return f"{header}\n\n{marker}{rest}"


TOP_LEVEL_NAME = re.compile(r"^(?:class )?([A-Za-z]\w*)(?:\(|: TypeAlias)", re.MULTILINE)


def declare_all(content: str) -> str:
    """Give the generated module an ``__all__``.

    The package re-exports every model from its root, which needs an explicit
    export list to survive a star import.
    """
    if "__all__" in content:
        raise SystemExit(
            f"Patch is now a no-op: the generator already declares __all__ - "
            f"delete the workaround ({REPORT})."
        )

    names = sorted(set(TOP_LEVEL_NAME.findall(content)))
    entries = "\n".join(f'    "{name}",' for name in names)
    declaration = f"__all__ = [\n{entries}\n]\n"

    # After the imports, which the first blank line following them ends.
    head, separator, tail = content.partition("\n\n\n")

    return f"{head}{separator}{declaration}{separator}{tail}"


def enums_to_literals(content: str) -> str:
    """Replace generated enum classes with ``Literal`` aliases.

    Two reasons, the first fatal. Members are named after their value, so the
    sandbox ``resources`` values come out as ``1X2 = "1x2"`` - not an
    identifier, and the module fails to compile. Beyond that a ``(str, Enum)``
    member renders as ``Class.MEMBER`` inside an f-string, which would turn
    `Status: FAILED` into `Status: SandboxResponseStatus.FAILED` in every error
    message. References to the alias need no rewriting.

    The plugin's own `enums: "literal"` option is a no-op for named schemas in
    @hey-api/openapi-python 0.0.24; drop this once it works.
    """

    def replace(match: re.Match[str]) -> str:
        values = ENUM_MEMBER.findall(match.group(2))
        return f"{match.group(1)}: TypeAlias = Literal[{', '.join(values)}]\n"

    patched: str
    patched, count = ENUM_CLASS.subn(replace, content)

    if not count:
        raise SystemExit(
            "Patch is now a no-op: no generated enum classes left. The plugin most likely "
            f'honours `enums: "literal"` now - delete the workaround ({REPORT}).'
        )

    return patched.replace("from enum import Enum\n", "", 1)


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TARGET

    if not target.is_file():
        raise SystemExit(f"Generated models not found at {target}.")

    content = target.read_text(encoding="utf-8")

    # The polymorphic pipeline "target" models are dead weight - the generator
    # already collapses TargetView/TargetViewWritable themselves to Any.
    content = drop_blocks(content, re.compile(r"^class Target"))

    content = defer_annotations(content)
    content = enums_to_literals(content)

    # Patch 1: hashid strings typed as int32 - unpatched, response validation
    # rejects every environment-scoped sandbox.
    for name in HASHID_MODELS:
        content = patch_block(
            content,
            class_block(name),
            lambda block: re.sub(
                r"^    id: Optional\[int\] = Field\(",
                "    id: Optional[str] = Field(",
                block,
                count=1,
                flags=re.MULTILINE,
            ),
            f"{name}.id should be a string (hashid), not an int",
        )

    # Patch 2: the create body really does take scope/environment. Unpatched,
    # our own request validation strips them before the call leaves the process.
    anchor = content.index("class ")
    content = content[:anchor] + ENVIRONMENT_REF + content[anchor:]

    for name in CREATE_BODY_MODELS:
        content = patch_block(
            content,
            class_block(name),
            lambda block: (
                block
                if re.search(r"^    scope:", block, re.MULTILINE)
                else append_fields(block, ENVIRONMENT_FIELDS)
            ),
            f"{name} is missing scope/environment",
        )

    # Patch 3: pydantic's smart union would let CreateNewSandboxRequestWritable
    # absorb a restore body and silently drop snapshot_id, turning a restore
    # into a blank sandbox.
    content = patch_block(
        content,
        class_block("AddSandboxBody"),
        lambda block: re.sub(
            r"^    root: (Union\[[^\n]*\])$",
            r'    root: Annotated[\1, Field(union_mode="left_to_right")]',
            block,
            count=1,
            flags=re.MULTILINE,
        ),
        "AddSandboxBody must match its union in declaration order",
    )

    content = declare_all(content)

    target.write_text(content, encoding="utf-8")

    # The generator wipes its output directory, so the package marker has to be
    # re-created here for the models to stay importable.
    (target.parent / "__init__.py").write_text("", encoding="utf-8")

    print(
        f"Cleaned up generated models (patched {len(CREATE_BODY_MODELS)} create-sandbox body models)"
    )


if __name__ == "__main__":
    main()
